package dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import androidx.annotation.Nullable;

public class SQLiteHelper extends SQLiteOpenHelper {
    public static final String DATABASE_NAME = "animals";
    public static final int DATABASE_VERSION = 12;

    //SQL sentence to create a table
    String sqlTableAnimals = "CREATE TABLE animals (codi INTEGER PRIMARY KEY, nomCientific TEXT, nomVulgar TEXT, descripcio TEXT, habitat TEXT, distribucio TEXT, rastre TEXT, fotoExcrement TEXT, fotoPetjada TEXT, fotoPetjades TEXT, fotoAnimal TEXT)";
    String sqlMusaranya = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (1, 'Crocidura russula', 'Musaraña común', 'Color grisáceo, poco contrastado entre la parte dorsal y el gris claro de la zona ventral. El color se oscurece en invierno y los juveniles presentan tonalidad gris en todo el cuerpo.', 'Asociado a muros de piedra, majanos u linderos que bordean pastizales, cultivos, corrales y afueras de pueblos. Se encuentra también en monte mediterráneo, robledales y choperas, hasta en prados montanos. En Sierra Nevada asciende hasta los 2000 metros, pero en la Cordillera Cantábrica no supera los 900 metros. Se distribuye en toda la península, excepto las cumbres más frías e Ibiza.', 'musaranyaDistri.png', '', 'musaranyaCaca.png', 'musaranya_petjada', 'NULL', 'musaranya.png');";
    String sqlTopillo = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (2, 'Talpa occidentalis', 'Topillo ibérico', 'Animal muy fácil de reconocer por si cuerpo robusto y cilíndrico, hocico rosado brillante , patas anteriores en forma de pala, ausencia de pabellones auriculares y denso pelaje negro aterciopelado, terminado en pequeña cola vertical. De rostro largo y estrecho, algo repuntado hacia arriba, manifiesta mayor cantidad de pelos blancos en el hocico  y las manos cavadoras.', 'Especie querenciosa de prados, cultivos frescos y regados y sectores de buen suelo orgánico, ni arenoso ni rocoso. También reside en bosques, más abundante en fresnedas, olmedas y choperas que en los montes de quercíneas y pinares, seleccionando áreas adehesadas y vaguadas. Lo mismo reside en el litoral que llega a cotas elevadas a 1700 metros.', 'topilloDistri.png', 'Animales excavadores especialistas en devorar lombrices, gusanos blancos y miriápodos, se detectas por los montones de tierra removida al final del sistema de túneles que habitan.', 'topilloCaca.png', 'topillo_petjada', 'NULL', 'topillo.png');";
    String sqlErizoEuropeo = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (3, 'Erinaceus europaeus', 'Erizo europeo', 'Inconfundibles por su recubrimiento de púas y la facilidad de enrollarse si se les molesta. Estas púas espinosas tienen tonos pardos cremosos con una banda negra cerca del ápice y miden en el dorso, entre 2-3 cm de longitud. Sus orejan no sobrepasan las puntas de las púas y es mas chato y oscuro que el Erizo Moruno. Exhibe una pequeña banda oscura entre hocico y ojos.', 'Especialista de filos boscosos y manchas arbustivas que lindan con áreas abiertas de pastizal y cultivos. Vive desde el nivel del mar al límite superior del arbolado. Más dependiente del ambiente ripario y los bosquetes aledaños a huertas y regadío en los medios mediterráneos. Hibernan entre octubre y marzo, menos tiempo en el sector mediterráneo peninsular.', 'erizoEuropeoDistri.png', 'Característicos excrementos apepinados desmenuzables, compuestos por cochinillas de la humedad y  insectos y semillas.', 'erizoCaca.png', 'erizoeuropeo_petjada', 'NULL', 'erizoEuropeo.png');";
    String sqlErizoMoruno = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (4, 'Atelerix algirus', 'Erizo moruno', 'Difícil de distinguir del erizo europeo, hay que fijarse en su pequeña talla, su coloración más clara y sus orejas que sobresalen por encima de las púas. Parece más hocicudo, de frente despejada y límite recto entre el pelo raso y las púas. Nocturno y crepuscular, de hábitos mal estudiados, parece no tener una hibernación generalizada, observándose individuos activos durante todo el año. Propenso a realizar sus madrigueras en huras de conejos.', 'Vive en el bosque y matorral termomediterráneo y en las terrazas de cultivos tales como olivos, almendros y algarrobos.','erizoMorunoDistri.png', 'Característicos excrementos apepinados desmenuzables, compuestos por cochinillas de la humedad y  insectos y semillas', 'erizoCaca.png', 'erizomoruno_petjada', 'NULL', 'erizoMoruno.png');";
    String sqlRataAgua = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (5, 'Arvicola sapidus', 'Rata de agua', 'Semiacuática, de cabeza chata, orejas redondeadas que casi no sobresalen del pelaje, dorso pardo oscuro con tonalidades rojizas y vientre gris sucio.', 'Especie ligada a márgenes de cursos de agua de caudal lento, con orillas excavables, y también en charcas, lagunas y marismas.', 'rataAiguaDistri.png', 'Observable pequeños montones de cagadas y acumulaciones de trozos de juncos y eneas, todos de igual tamaño, entre la vegetación palustre de márgenes de arroyos y acequias.', 'rataAiguaCaca.png', 'rata_aigua_petjada', 'NULL', 'rataAgua.png');";
    String sqlRataAlmizclera = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (6, 'Ondatra zibethica', 'Rata almizclera', 'Corpulento roedor anfibio reconocible por su densa capa pardo oscura de la que salen largos pelos salpicados, y pecho plateado. Pies posteriores semipalmeados. El rasgo inconfundible es la forma de la cola, larga y escamosa, negra y, aplanada lateralmente. Su altura es el tripe que la anchura. Excelente nadadora y buceadora, vegetariana y nocturna. \n \n Fue introducida en 1905 en Checoslovaquia, en granjas peleteras. Escapada de cautividad, ha ocupado casi toda Europa, convirtiéndose en plaga de ríos y humedales.', 'Especialista de marismas y vegetación palustre.', 'rataAlmizcleraDistri.png', 'Deja pasillos de unos 20 cm en la vegetación palustre y pilas de excrementos, verdes o negruzcas del tamaño de huesos de aceitunas, en la boca de las galerías, surtidas de tubos de ventilación. Deja típicas huellas estrelladas, de las cinco uñas, mayores atrás (7 x 5 cm) que delante (3,5 x 3 cm).', 'rataAlmizcleraCaca.png', 'rata_almizclera_petjada', 'NULL', 'rataAlmizclera.png');";
    String sqlRaton = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (7, 'Apodemus sylvaticus', 'Ratón de campo', 'Dorso pardo grisáceo y vientre blanco sucio sin mucho contraste, con cola fina. Pequeña mancha amarillenta, alargada, en la garganta. Ojos grandes y negros muy prominentes. \n \n Nocturno, aunque las hembras preñadas presentan una actividad diurna en verano.', 'Roedor muy adaptable, capaz de habitar desde bosques de todo tipo de matorrales, cultivos, pastizales, dunas y toda clase de linderos. En las tierras agrícolas se refugia en los bosques isla cuando llega el invierno.', 'ratonCampoDistri.png', 'NULL', 'ratonCampoCaca.png', 'raton_campo_petjada', 'NULL', 'ratonCampo.png');";
    String sqlRataParda = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (8, 'Rattus norvegicus', 'Rata parda', 'Robusta de cola algo corta. Fácil de distinguir de la Rata Negra por su hocico bastante romo y orejas más cortas y gruesas. Pelaje de color gris pardusco, con el vientre blanco sucio o amarillento. \n \n Muy buena buceadora, pero no trepa como la Rata Parda. Esperanza de vida corta, menos de 18 meses, aunque con un gran número de descendientes anuales, alrededor de 56.', 'En poblaciones urbanas se alimentan de desperdicios y viven en bajos, sótanos y cloacas. En el campo, reside en lugares húmedos con vegetación densa, sobre todo en parcelas de regadío, arrozales, marismas y bordes de cursos de agua.', 'rataPardaDistri.png', 'Se puede diagnosticas la especie de rata por el tamaño de los excrementos, tras dividir su diámetro por longitud, si el resultado es un valor de 0,42 a 0,56, son de Rata Parda, y su es de 0,31 a 0,37 pertenecen a la Rata Negra.', 'rataPardaCaca.png', 'rata_parda_petjada', 'NULL', 'rataParda.png');";
    String sqlRataNegra = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (9, 'Rattus rattus', 'Rata negra', 'Más pequeña y esbelta que la rata parda, con hocico puntiagudo, cola muy larga y fina, y aspecto más orejudo que su vecina. Coloración variable, por lo general más oscura en ambientes urbanos y leonados en el campo.', 'Cosmopolita, pero en las zonas templadas es desplazada por la Rata Para y se acantona en casas. Elige en los núcleos urbanos los desvanes y altillos de las casas, lejos de los sótanos y cloacas que ocupa su competidora. En el campo vive en olivares y zarzales. Hace nidos tanto en el suelo, entre raíces como en ramas de arbolado perenne.', 'rataNegraDistri.png', 'Se puede diagnosticas la especie de rata por el tamaño de los excrementos, tras dividir su diámetro por longitud, si el resultado es un valor de 0,42 a 0,56, son de Rata Parda, y su es de 0,31 a 0,37 pertenecen a la Rata Negra.', 'rataNegraCaca.png', 'rata_negra_petjada', 'NULL', 'rataNegra.png');";
    String sqlLiron = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (10, 'Eliomys quercinus', 'Lirón careto', 'Los juveniles presentan gris dorsal y blanco sucio ventral. Su tamaño aumenta hacia el sur, y disminuye con la altitud. Se describen 4 subespecies españolas. La raza lusitanicus, del sudoeste peninsular, de coloración más rojiza, raza quercinus, que ocupa el resto del área peninsular, con un menor tamaño, un colorido más pálido y una cola ventralmente blanca. En Mallorca y Menorca reside gymnesicus, de peso mediano y rabo blanco. Y en Formentera, reside ophiusae, la subespecie más robusta, de color oscuro y cola negra.', 'Roedor generalista, muy versátil. Frecuente en zonas pedregosas pero también en matorral denso y todo tipo de bosques. Les gustan mucho los lugares con piedras y rocas rodeados de vegetación.', 'lironDistri.png', 'Visibles sus nidos de verano hecho de trozos de ramas y follaje.', 'lironCaca.png', 'liron_petjada', 'NULL', 'lironCareto.png');";
    String sqlArdilla = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (11, 'Sciurus vulgaris', 'Ardilla roja', 'Roedor arborícola caracterizado por su larga y muy poblada cola, de pelaje dorsal rojizo y partes inferiores blancas. Es uno de los mamíferos que presenta mayor variedad en coloraciones. \n \n Especie diurna, magnifica trepadora con su colar ondulante. Desciende del tronco cabeza abajo, en trayectoria sinuosa. Apeona de forma errática, con el rabo recto, haciendo frecuentes paradas en las que vigila erguida sobre los cuartos traseros con las orejas tiesas y el hocico olfateante. Intenta pasar desapercibida inmovilizándose plana sobre la corteza o situándose en la cara del tronco oculta al observador.', 'Especialista forestal, adaptada a las frondosas eurosiberianas (roble, castaño, haya) y a todo tipo de coníferas (abeto, pinos, alerces) y bosques mixtos. Puede colonizar pinares isla gracias a su capacidad de atravesar terrenos desarbolados. No ocupa encinares.', 'ardillaDistri.png', 'Muy chillona, escuchándose de lejos en el bosque un castañeo (chuk – chuk – chuk). Hace nidos en las copas de los arboles, por lo general a bastante altura, más de 8 m, compactos, esféricos, de unos 30 cm de diámetro, anclados en una bifurcación de ramaje cercana al fuste.', 'ardillaCaca.png', 'ardilla_petjada', 'NULL', 'ardilla.png');";
    String sqlLiebre = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (12, 'Lepus granatensis', 'Liebre ibérica', 'De color marrón ocre rojizo, entreverado en negro en el lomo, y contrastado vientre blanco. La superficie blanca se extiende por las patas posteriores y anteriores.', 'Hábitat muy variado, desde las marismas y pastizales litorales a los prados de alta montaña. Más común en campos de cereal, viñas, olivares y matorral ralo que en áreas de vegetación arbustiva o arbolada densas.', 'liebreDistri.png', 'Las liebres se detectan fácilmente por sus excrementos, mayores (15 a 20 mm de diámetro) que los del conejo y algo aplanados, no totalmente esféricos, esparcidos o en pequeños acúmulos, pero sin formar cagarruteros.', 'liebreCaca.png', 'liebre_petjada', 'NULL', 'liebre.png');";
    String sqlConejo = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (13, 'Oryctolagus cuniculus', 'Conejo', 'Tamaño mediano y color gris pardo, con una mancha marrón en la zona posterior del cuello y vientre blanco sucio. Cola bicolor gris arriba y blanco abajo. Orejas largas de color marrón uniforme, sin mancha negra en sus puntas. Ojos grandes y negros. Los ejemplares del norte peninsular son mayores que los del sur y las islas. \n \n Animales muy sedentarios que viven en grupos sociales, compartiendo su vivar, el cual no se alejan más de 200 m.', 'El hábitat optimo en España coincide con el clima mediterráneo de verano, caluroso y lluvias de unos 500mm, terreno ondulado, de suelo excavable y una combinación de monte (20%), matorral (30%), pastizal (35%) y terreno desnudo (15%), con un arroyo cercano y altitud inferior a 1000m.', 'conillDistri.png', 'Fácil de detectar pos los cagarruteros, cúmulos de excrementos esféricos y oscuros (7 a 12 mm de diámetro), a veces cercanos a carriles que salen de las bocas y por las escarbaduras superficiales del suelo que miden 5 a 15 cm de largo, sin profundizar más de 10 cm.', 'conillCaca.png', 'conill_petjada', 'NULL', 'conill.png');";
    String sqlOso = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (14, 'Ursus arctos', 'Oso pardo', 'Inconfundible por su gran tamaño, cuerpo rollizo, orejas pequeñas y redondeadas y cola muy corta. Color variable, desde el rojizo pardo oscuro. Son frecuentes las marcas blancuzcas en lo alto del cuello. Los osos españoles se caracterizan por las patas negras y tener amarillenta la punta del pelo. La hembra es más fina que el macho y pesa una cuarta parte menos. Los oseznos suelen presentar un collar blancuzco que desaparece al crecer. \n \n Animal nocturno con máximos de actividad al oscurecer y amanecer. Se mueve a tranco lento pero puede correr más rápido que una persona. Ágil en terreno abrupto y capaz de trepar a los arboles.', 'Hibernan en un osil, habitualmente una cavidad natural en peñas secas de cuarcita, donde confeccionan un nido de ramas, brezo y hierba. Al principio de la primavera, pasta hierba tierna en las camperas de piornal. \n \n La mediocre calidad del hábitat en pirineos y las montañas cantábricas origina una gran movilidad y grandes dominios vitales en nuestros osos, dependientes de una onda estacional que, de primavera  al invierno, pasa de hierba tierna a los arándanos, con frecuentes tendencias al carroñeo.', 'osoDistri.png', 'Plantígrado delatado por huellas  inconfundibles que recuerdan a una pisada humana. Mano más corta y ancha que el pie, con anchura que no sobrepasa los 18 cm. \n \n Excrementos en forma de gran plasta, distinguiéndose, cuando ha comido  hierba, de los propios de vacas y caballos por su olor dulzón a mermelada y mínima trituración de los fragmentos vegetales.', 'osoCaca.png', 'oso_petjada', 'NULL', 'oso.png');";
    String sqlLobo = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (15, 'Canis lupus ssp. signatus', 'Lobo ibérico', 'Subespecie caracterizada por tener manchadas la parte externa del rabo y la cara de negro, al igual que la cara anterior de las patas delanteras. Suelen ser más oscuros los ejemplares del norte que los del sur. Con pelaje más canela en la zona ventral y patas, largo y oscuro cuello, lomo y cola. El colorido individual es variable. En verano, al perder la borra, parecen más esbeltos y delgados. \n \n Costumbres nocturnas, capaz de recorrer entre 10 y 50 km por la noche. Vive en péquelas familias compuestas por la pareja reproductora, las crías del año y los individuos de años anteriores. Los miembros de estas manadas, por lo general de menos de 10 individuos, suelen alimentarse bien solitarios o en pequeños grupos. Poco aulladores, quizá adaptados a un medio muy humanizado donde siempre se les ha perseguido.', 'El lobo es muy acomodaticio y reside en amplia gama de paisajes, desde la campiña gallega y las brañas cantábricas a los pastos de cereal de secano con encinares cerca del Duero, y las fincas de monte mediterráneo y ciervos del área de Extremadura y Andalucía. La paridera ocurre de abril a junio. La hembra sitúa la lobera en enclaves de vegetación densa cercanos al agua, repoblaciones cerradas de pinos, cárcavas, riscos y más rara vez, en zorreras o tejoneras aisladas.', 'loboDistri.png', 'Huellas más empaquetadas y alargadas que los perros, con almohadilla interdigital grande, fuertemente escotada por atrás. \n \n Excrementos cilíndricos más grandes que los perros (5 – 22 cm)  y no retorcidos. Malolientes y contienen gran cantidad de pelos y hueso. Se encuentras sobre matitas en cruces de caminos.', 'loboCaca.png', 'lobo_petjada', 'NULL', 'lobo.png');";
    String sqlZorro = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (16, 'Vulpes vulpes', 'Zorro', 'Cánido inconfundible por largo y peludo rabo horizontal terminado en punta blanca. Orejas puntiagudas, negras por fuera, al igual que las calzas. Pelaje bastante variable con tonalidades rojizas, amarillentas y grises, incluso ejemplares negruzcos. Los hay con barbero blanco, plateado o negro. En época de celo, el barbero de las hembras presentan tintes rosados. \n \n Actividad esencialmente nocturna, entrando en actividad a la media hora de ponerse el sol, hasta las dos horas después de amanecer. Come de todo, aunque sus presas predilectas son ratones y topillos en el norte, y conejos en el sur.', 'Las mayores densidades se dan en ambientes heterogéneos de bosquetes, cultivos, basureros y granjas, pero es capaz de residir en zonas subalpinas y todo tipo de montes. Ocupa toda la península pero falta en baleares y canarias.', 'zorroDistri.png', 'Marca unas pisadas más largas y ovaladas que las de lso perros pequeños, que  imprimen los cuatro dedos y sus uñas. \n \n Excrementos de 5 a 20 cm de largo, oscuros y pestilentes, más consistentes que los caninos, habitualmente con pelos que entrelazan los trozos de la cadena. Frecuentemente sobre piedras, toperas o en los senderos.', 'zorroCaca.png', 'zorro_petjada', 'NULL', 'zorro.png');";
    String sqlComadreja = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (17, 'Mustela nivalis', 'Comadreja', 'Diminuto carnívoro de cuerpo cilíndrico y cortas patas. Dorso y cola de color marrón claro y parte ventral blanca desde el labio inferior al ano.  Con frecuencia se levanta sobre las patas traseras. Las comadrejas del norte peninsular (Subs. vulgaris) presentan una línea ondulada, irregular, entre el manto pardo y el blanco ventral, aparte de una mancha marrón debajo de la mejilla, mientras que los ejemplares del sur de la península (Subs. iberica)  tienen una línea de separación recta, los pies blancos y carecen de mancha parda bajo la mejilla.', 'Especie extendida desde el litoral a las pedrizas de alta montaña, siendo muy visible en muros de piedra, montones de leña, setos y bordes de las casas en las aldeas.', 'comadrejaDistri.png', 'Excrementos pequeños entre 3 – 5 cm  de longitud y 2 – 3 cm de diámetro retorcidos, negros y terminados en pequeño mechón peludo.', 'comadrejaCaca.png', 'comadreja_petjada', 'NULL', 'comadreja.png');";
    String sqlTuron = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (18, 'Mustela putorius', 'Turón', 'Típica mascara blancuzca que abarca el hocico, mentón y sendas bandas tras los ojos. Pelaje marrón oscuro en el lomo, más claro en los flancos y negro en la panza. En verano son mucho más oscuros que en invierno. \n \n El macho casi dobla en tamaño a la hembra. Marcha a saltos con la espalda arqueada y frecuentes posturas erguidas sobre las patas posteriores. Muy gritón con gran variedad de gruñidos y chasquidos cuando se alarma.', 'Adaptable a diversos ambientes, pero más común en bordes de arroyos o en montes con cados de conejos (conjunto de túneles creados por los conejos).', 'turonDistri.png', 'Distancia de saltos corta, de 40 – 60 cm. \n \n Excrementos negros y largos, de hasta 7 cm, retorcidos y de extremos afilados. Depositados en letrinas junto a las madrigueras.', 'turonCaca.png', 'turon_petjada', 'NULL', 'turon.png');";
    String sqlMarta = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (19, 'Martes martes', 'Marta', 'Barbero amarillo o anaranjado no dividido. Pelaje pardo oscuro y nariz negra. La borra de los flancos es oscura. Pies muy peludos. Diferenciable de todos los mustélidos por sus extremidades. \n \n Trepadora agilísima y curiosa que asciendo por los troncos abrazándolos como la ardilla. Capaz de tirarse al suelo desde copas de 20 metros de altura. Caza mas en el suelo que en los arboles. Se encama en nidos viejos de ardillas y rapaces, rara vez en tejoneras.', 'Reside en bosques eurosiberianos lo mismo en coníferas, frondosas que en rodales mixtos. Prefiere arbolado maduro, hasta los 2000 m de altitud en las montañas norteñas peninsulares. En baleares ocupan pinar carrasco, encina, sabinar y garrigas.', 'martaDistri.png', 'Excrementos de olor mas dulzón pero sin aroma  almizcle. Muy retorcidos y de extremos afilados. Se depositan en las pistas forestales sobre piedras o protuberancias cada 100 – 200 metros, nunca en letrinas.', 'martaCaca.png', 'marta_petjada', 'NULL', 'marta.png');";
    String sqlGarduña = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (20, 'Martes foina', 'Garduña', 'Caracterizada por la mancha blanca que desde el cuello baja y se bifurca  hasta el arranque de las patas delanteras. Más pesada, corpulenta y paticorta que la marta, con orejas pequeñas y estrechas, pies poco peludos y hocico mas achatado. Colorido que varía del pardo oscuro al rojizo, este último más frecuente en ejemplares meridionales.', 'Animal muy adaptable, extendido por toda la península, tanto en bosques, matorrales y roquedos como en ambientes rurales y suburbanos.', 'gardunyaDistri.png', 'Pata trasera ligeramente más largo que las delanteras, con la plantilla interdigital  que se presenta bien cuadriculada y formada por cuatro o cinco bloques. \n \n Excrementos largos y retorcidos, de tufo desagradable, afilados en un extremo, que deposita en letrinas.', 'gardunyaCaca.png', 'gardunya_petjada', 'NULL', 'gardunya.png');";
    String sqlNutria = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (21, 'Lutra lutra', 'Nutria', 'Observada por lo general junto al agua, con cuerpo fusiforme y cortas patas palmeadas y larga cola, ancha en la base y estrecha en la punta. Pelambrera corta y parda, pasando a gris sucio en la cara ventral y blancuzca en la garganta. Mojado pelaje parece liso y suave, pero al secarse se aglutinan los mechones y resulta algo desflecado.\n \n Buceo silencioso y elegante, que suelen durar entre 10 y 40 segundos. Observa con los dos ojos y la nariz sobre la lámina de agua. Se mueve en tierra con aspecto giboso y con el tranco a saltos en cortas distancias. Carácter juguetón, siendo común que saque y manipule cantos redondeados tras las zambullidas.', 'Vive en ríos, embalses, marismas y, unas pocas, en la costa. Requiere peces, tranquilidad moderada y orillas que conserven el soto con bajo grado de contaminación.', 'nutriaDistri.png', 'Huellas de forma redondeada que marcan los cinco dedos y las pequeñas uñas, casi circular la delantera y un poco más alargada la trasera. Camina a saltos. \n \n Excrementos que aparecen en piedras grandes, raíces de arboles corpulentos, escolleras y bajo pilares de puentes, compuestos por escamas y espinas de peces, con restos de cangrejos, que se deshacen al cogerlos, de olor dulce.', 'nutriaCaca.png', 'nutria_petjada', 'NULL', 'nutria.png');";
    String sqlTejon = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (22, 'Meles meles', 'Tejón', 'Constitución ancha y robusta con cabeza blanca cruzada por bandas negras laterales que incorporan la zona ocular. Observado a distancia parece gris, color fruto de un pelo blanco en su base y ápice, y de banda negra en el centro. Patas y vientre cubiertos por pelo negro bastante ralo en el abdomen.\n \n Se mueve al trote con la cabeza baja y los cuartos traseros balanceándose de un lado a otro, alternando con paradas para escuchar.', 'Tejoneras de muchas bocas y complicada red de galerías y cámaras. Se diferencia de las zorreras por verse fuera montones de tierra y vegetales secos, resultado de la renovación de las camas. Viven en todo tipo de montes y dehesas, aunque no les impide la residencia en áreas cultivadas, campiñas, riveras o cantiles. Más numerosos en mosaicos de bosque con cultivos y pastizales.', 'tejonDistri.png', 'Huella inconfundible por marcar los 5 dedos y las filas de las garras hacia delante, abiertos en un arco estrecho. \\n \\n Excrementos cilíndricos más deleznables que los del perro y depositados en pequeñas letrinas excavadas, tanto cerca de la madriguera como en los bordes del dominio vital.', 'tejonCaca.png', 'tejon_petjada', 'NULL', 'tejon.png');";
    String sqlMeloncillo = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (23, 'Herpestes ichneumon', 'Meloncillo', 'Cabeza fina, cuerpo alargado, paticorto y cola singular, larga y poblada, ancha en su arranque y termina en un mechón de fuertes cerdas negruzcas. Pelaje negro punteado en amarillo. Garra no retráctiles. Pupila horizontal, rasgo excepcional entre los carnívoros.\n \n Es el carnívoro español más diurno, muy visible en su deambular desgarbado, reptiliano, sin apreciarse las patas, ocultas por el largo pelo colgante. Ni solitario ni social, es frecuente ver a la madre seguida de una a tres crías.', 'Típico del monte mediterráneo de madroño, olivillas, lentiscos y jaguarzos con encinas y alcornoques. En las zonas de campiña y cultivos se refugia en los sotos cubiertos de fresnos, adelfas y zarzas. Cazador generalista, sobre todo de gazapos y reptiles.', 'meloncilloDistri.png', 'Huellas semiplantígradas (5 – 6 cm de largo por 3 – 4 cm de ancho) que marcan los cinco dedos, y en suelo arenoso, dejan atrás la estela del rabo. \n \n Excrementos alargados (10 – 15 cm y 2 de diámetro) y negros, depositados en letrinas en caminos o bordes de zarzales, muchas veces con pelos jaspeados blanquinegros del propio ejemplar.', 'meloncilloCaca.png', 'meloncillo_petjada', 'NULL', 'meloncillo.png');";
    String sqlGineta = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (24, 'Genetta genetta', 'Gineta', 'Aspecto grácil y alargado, mas delgada que un gato. Colorido pardo grisáceo plagado de motas negras en el cuerpo, que a veces se agrupan en franjas longitudinales. Largo rabo con anillos oscuros y claros. Morro afilado y orejas largas, con patas cortas. Garras semirretráctiles. Hocico muy contrastado, negro rodeado de nariz y mancha subocular blanca. \n \n Excelente trepadora, muy agil y flexible, ayudada por su cola que actúa como timón estabilizante. Buena nadadora. Muy buena vista que le permite la caza al acecho y la captura de presas mediante sus garras.', 'Especie muy versátil, lo mismo habita en bosques y matorrales que lugares rocosos. En las vegas cultivadas se refugia en los sotos y las acequias con carrizos, eneas y sauces. Muy común en las dehesas de encinas y alcornoques, y en los olivares. Capaz de adaptarse a la vecindad de pueblos, ralea en alta montaña, aunque hay citas hasta los 2.500m de altitud.', 'ginetaDistri.png', 'Huellas pequeñas, raramente más de 4 x 4 cm, con cuatro almohadillas, garras sin marcar y una plantilla de aspecto triangular formada por tres lóbulos fusionados. En suelo blando, se marca el quinto dedo, excéntrico. \n \n Sus excrementos son gruesos y largos comparados con el tamaño del animal. Aparecen doblados en herradura, de 20 cm de largo y 2 cm de ancho, negruzcos en fresco, de olor no repelente y muchas veces en grandes cagarruteros sobre rocas.', 'ginetaCaca.png', 'gineta_petjada', 'NULL', 'gineta.png');";
    String sqlLince = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (25, 'Lynx pardinus', 'Lince ibérico', 'Felino endémico de corpulencia mediana, patas largas y corta cola, terminada en extremo negro. Cara inconfundible en la que destacan las patillas puntiagudas, más desarrolladas en los adultos, y los pinceles negros en las puntas de las orejas. Pelaje leonado, salpicado por manchas negruzcas. \n \n Animal solitario, crepuscular y nocturno, más fácil de observar durante el día en jornadas lluviosas de invierno. Adultos territoriales, residentes en dominios exclusivos donde no permiten la intrusión de ningún ejemplar de su sexo.', 'Especialista del monte mediterráneo tranquilo que combina densa cobertura vegetal y calveros con hierba para los conejos, su principal alimento. Esta estructura de un hábitat poco humanizado y en mosaico, de cobertura superior al 60%, se encuentra tanto en el monte de pinos, brezos y jaguarzos de Doñana como en sierras mediterráneas, hasta altitudes de 1.300 metros.', 'linceDistri.png', 'Deja típicas huellas en veredas, cruces de caminos y cortafuegos, redondeadas, con cuatro dedos abiertos en arco que no marcan las garras. La anchura entre el borde externo y las plantillas digitales varía entre los 68 mm de machos adultas y algo más de 40 mm en hembras y crías. \n \n Las cagadas del Lince Ibérico son largas y rectas, puntiagudas en ambos extremos y de color gris ceniza. Se componen de huesos, dientes y pelo gris de Conejo, y las deposita, sin enterrarlas, en letrinas vecinas a orines y vegetación arañada. Miden hasta 25 cm de largo.', 'linceCaca.png', 'lince_petjada', 'NULL', 'lince.png');";
    String sqlGatoMontes = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (26, 'Felis silvestris', 'Gato montés', 'Siempre más fuerte y corpulento que el gato doméstico,, con rayado oscuro vertical y cola muy gruesa, terminada en porra negra. Color del pelaje gris, con una sola banda negra a lo largo del espinazo y brazos recorridos por dos franjas negras. Al contrario que los gatos caseros, nunca presenta motas negras ni rojizas, y sus marcas blancas se restringen a la quijada, garganta y zona debajo del culo. \n \n Muy activo al alba y al ocaso, y muy buenas posibilidades de observarlo cuando se calienta con los primeros rayos del sol en la linde del matorral con claros. Los terrenos de caza corresponden a zonas abiertas de camperas de matorral, praderas y filos boscosos.', 'Hábitat variado, poco humanizado, sobre todo en los bordes de manchas de frondosas de baja y media montaña, frecuentemente encamado en matorral denso y afloramientos rocosos. Extendido en toda España, aunque falta en las franjas costeras urbanizadas y en el secano desarbolado.', 'gatDistri.png', 'Huellas típicas, de 6 cm de largo y 5 cm de ancho, con 4 almohadillas delanteras y una plantilla interdigital grande trilobulada. Las huellas de los gatos domésticos no superan los 4 x 4 cm y parecen más cuadradas. \n \n Sus excrementos, a diferencia del Lince Ibérico, son de 4 a 8 cm de largo y 1,5 cm de diámetro, cilíndricas, algo retorcidas y apuntadas en sus extremos, más a menudo sobre objetos prominentes (piedras, macollas) que en pequeñas letrinas abiertas.', 'gatCaca.png', 'gatomontes_petjada', 'NULL', 'gatMontes.png');";
    String sqlJabali = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (27, 'Sus scrofa', 'Jabalí', 'Facilísimo de reconocer por su cuerpo rechoncho, cabeza rematada en jeta, patas cortas y pequeño rabo terminado en mechón de pelos negros, dejando en el ambiente un tufo inconfundible. Se pueden apreciar tres clases de edad. Con menos de 6 meses son rayones, con 11 típicas rayas  negras sobre fondo amarillento. Los jabatos de 6 a 12 meses, cabeza corta, pelambrera rojiza y rabo sin mechón. Y con más de un año son adultos, provistos de largas cerdas y una crin dorsal que recorre todo el lomo. Pelaje invernal más largo y abundante, con densa borra. \n \n Animal estrictamente nocturno. Forma piaras integradas por hembras y descendientes. Los machos adultos tienden a la vida solitaria, a veces acompañados de otro subadulto, llamado escudero.', 'Especie polivalente, en principio bien adaptada al ambiente forestal, capaz de acomodarse también a bosquetes, riberas y cultivos de regadío.', 'jabaliDistri.png', 'Huellas inconfundibles al marcar las dos pezuñas principales, y, detrás, las dos laterales. Amigos de rebozarse en el fango, crean excavaciones de 1’5 m de largo y medio metro de hondo, donde se revuelcan antes de restregarse en algún tronco cercano. \n \n Excremento maloliente y oscuro, a partir de plastas circulares (4 – 5 cm de diámetro) que se agrupan en forma de morcilla. Gruñe y resuella cuando busca comida. Amenazado, chasquea agresivamente la dentadura.', 'jabaliCaca.png', 'jabali_petjada', 'NULL', 'jabali.png');";
    String sqlMuflon = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (28, 'Ovis orientalis', 'Muflón', 'Carnero mediterráneo de pelo corto y color marrón achocolatado, con manchas blancas en los flancos (solo en los machos), patas, cara y región caudal. El macho posee unos grandes cuernos curvados en círculo que crecen y añaden medrones con la edad. \n \n Especie diurna, muy activa al amanecer y al crepúsculo. Conducta social, en rebaños separados durante primavera y verano: hembras y jóvenes por un lado y  machos por otro.', 'Acepta varios tipos de hábitat, aunque en su origen prefiere matorral mediterráneo con rocas. También se ha adaptado a los pinares de Andorra y a os pinares y codesales canarios en las Cañadas del Teide. Aquí con impacto negativa sobre la flora autóctona.', 'muflonDistri.png', 'Huellas casi idénticas a las de la oveja, de dos pezuñas con las puntas claramente separadas (6 cm de largo y 4,5 cm de ancho). \n \n Produce masas de excrementos de 10 a 15 cm de largo, cuyas unidades adoptan formas de facetas rectas entre la plasta.', 'muflonCaca.png', 'muflon_petjada', 'NULL', 'muflon.png');";
    String sqlCabra = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (29, 'Capra pirenaica', 'Cabra montés', 'Especie ibérica endémica. Pelaje grisáceo en invierno y marrón canela en verán, con manchas negras en los flancos y en las patas que incrementan su extensión con la edad. Macho coronado por una vistosa lira, cornamenta que alcanza los 75 cm  o más de curvatura, con crin y barba características. \n \n Realizan movimientos trashumantes, hacia solanas y bajos de ladera en invierno, y más altor en verano y otoño. Los machos realizan desplazamientos más acusados y ascienden a mayores cotas.', 'Es un ungulado amigo de las zonas escarpadas de sierra a altitudes que oscilan entre los 500m y los 2500m. Lo mismo habita bosques montanos de pino, encinas o melojos que formaciones arbustivas, sean piornales, brezales o enebrales de monte mediterráneo.', 'cabraDistri.png', 'Huellas de las pezuñas 7 x 4 cm y cagadas cilíndricas (20 x 10 mm) en los machos y esféricas (11 x 9 mm) en las hembras. \n \n Las cagarrutas son cilíndricas, poco adhesivas.', 'cabraCaca.png', 'cabra_petjada', 'NULL', 'cabra.png');";
    String sqlCiervo = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (30, 'Cervus elaphus', 'Ciervo Rojo', 'Impresionante animal de pelaje rojizo en verano y grisáceo en invierno, adornado con una arboladura ramificada en puntas. La cierva mide entre un tercio y la mitad de un macho. El aspecto y desarrollo de la cuerna permiten definir varias clases de edad masculinas. Hasta los 6 -7 meses, los cervatillos carecen de cornamenta. De esta edad hasta el año, emergen en la cabeza dos mínimos pivotes. Entre uno y dos años son varetos, y al año siguiente horquillones. A partir de ahí, el ciervo rojo exhibe una cornamenta, cuyas puntas no tienen que ver con la edad.', 'Habita en medios muy variados, desde los bosques y matorrales de montañas frescas, a los pinares de repoblación, dehesas o las sierras mediterráneas.', 'ciervoDistri.png', 'La huella de las dos pezuñas es grande. El borde convexo anterior de su punta externa contrasta con lo recto del borde interno. La presencia del ciervo rojo se aprecia por sus efectos en la vegetación, unos debidos al ramoneo del brote principal, que achaparra pinos, y otros al desprender el correal de la cuerna frotándola con arboles jóvenes.\n \n Presenta un excremento voluminoso (2 cm de largo y 1,5 cm de diámetro), redondeado por un ápice en la hembra y con pinta de bellota en el venado.', 'ciervoCaca.png', 'ciervo_petjada', 'NULL', 'ciervo.png');";
    String sqlCorzo = "INSERT INTO animals (codi, nomCientific, nomVulgar, descripcio, habitat, distribucio, rastre, fotoExcrement, fotoPetjada, fotoPetjades, fotoAnimal) VALUES (31, 'Capreolus capreolus', 'Corzo', 'Del tamaño de una cabra, y sin cola aparente, rojizo en cercano y gris parduzco en invierno, visible a distancia por la culera blanca, con aspecto de balón doble en el macho y de corazón invertido en la hembra. Hocico inconfundible de narices negras y reborde blanco en los labios. \n \n Cuerna masculina que se inicia en el corcino con dos pivotes de no más de 3 cm. Al año de vida, la nueva cuerna exhibe dos perchas tan altas como las orejas. Con dos años es un horquillón, de astas bifurcadas, y la tercera cabeza es y a la típica de tres puntas de unos 35 cm de longitud', 'Hábitat forestal, sobre todo en bosques que ofrecen prados, linderos y camperas. Lo mismo frecuenta hayedos, robledales y melojares que pinares o riberas. En el piso termomediterráneo selecciona barrancos frescos de encinas, alcornoques y quejigos con subvuelo de madroñal, lentisco y brezo.', 'corzoDistri.png', 'Huellas de las dos pezuñas muy estrechas y alargadas (4’5 cm de largo y 3 cm de ancho).Los machos marcan su territorio destrozando arbolitos de 30 – 70 cm del suelo. Al pie de los arbolitos deja un sector de suelo rascado con las manos. \n \n Excrementos cilíndricos alargados (14 x 16 mm), puntiagudos, negros y dispuestos en cúmulos.', 'corzoCaca.png', 'corzo_petjada', 'NULL', 'corzo.png');";


    //The constructor: Create the database. Pay attention to your Android API level
    public SQLiteHelper(Context context){
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }

    //Called if DB is accessed but not created yet
    @Override
    public void onCreate(SQLiteDatabase db){
        db.execSQL(sqlTableAnimals);    db.execSQL(sqlMusaranya);
        db.execSQL(sqlTopillo);        db.execSQL(sqlErizoEuropeo);
        db.execSQL(sqlErizoMoruno);        db.execSQL(sqlRataAgua);
        db.execSQL(sqlRataAlmizclera);        db.execSQL(sqlRaton);
        db.execSQL(sqlRataParda);        db.execSQL(sqlRataNegra);
        db.execSQL(sqlLiron);        db.execSQL(sqlArdilla);
        db.execSQL(sqlLiebre);        db.execSQL(sqlConejo);
        db.execSQL(sqlOso);        db.execSQL(sqlLobo);
        db.execSQL(sqlZorro);        db.execSQL(sqlComadreja);
        db.execSQL(sqlTuron);        db.execSQL(sqlMarta);
        db.execSQL(sqlGarduña);        db.execSQL(sqlNutria);
        db.execSQL(sqlTejon);        db.execSQL(sqlMeloncillo);
        db.execSQL(sqlGineta);        db.execSQL(sqlLince);
        db.execSQL(sqlGatoMontes);        db.execSQL(sqlJabali);
        db.execSQL(sqlMuflon);        db.execSQL(sqlCabra);
        db.execSQL(sqlCiervo);        db.execSQL(sqlCorzo);
        System.out.println("creada BD");
    }

    //Called if db version is increased in your app code
    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion){
        //Deleting the preiovus versin on the table
        db.execSQL("DROP TABLE IF EXISTS animals");
        db.execSQL(sqlTableAnimals);
        db.execSQL(sqlMusaranya);        db.execSQL(sqlTopillo);
        db.execSQL(sqlErizoEuropeo);        db.execSQL(sqlErizoMoruno);
        db.execSQL(sqlRataAgua);        db.execSQL(sqlRataAlmizclera);
        db.execSQL(sqlRaton);        db.execSQL(sqlRataParda);
        db.execSQL(sqlRataNegra);        db.execSQL(sqlLiron);
        db.execSQL(sqlArdilla);        db.execSQL(sqlLiebre);
        db.execSQL(sqlConejo);        db.execSQL(sqlOso);
        db.execSQL(sqlLobo);        db.execSQL(sqlZorro);
        db.execSQL(sqlComadreja);        db.execSQL(sqlTuron);
        db.execSQL(sqlMarta);        db.execSQL(sqlGarduña);
        db.execSQL(sqlNutria);        db.execSQL(sqlTejon);
        db.execSQL(sqlMeloncillo);        db.execSQL(sqlGineta);
        db.execSQL(sqlLince);        db.execSQL(sqlGatoMontes);
        db.execSQL(sqlJabali);        db.execSQL(sqlMuflon);
        db.execSQL(sqlCabra);        db.execSQL(sqlCiervo);
        db.execSQL(sqlCorzo);
        System.out.println("actualitzada BD");
    }
}
